# Generated by Django 3.0.2 on 2020-07-21 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_species'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='img',
            new_name='image',
        ),
    ]
