# Generated by Django 3.0.2 on 2020-07-23 16:32

from django.db import migrations, models
import index.utils


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200721_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to=index.utils.photo_path),
        ),
        migrations.CreateModel(
            name='ShapeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=index.utils.photo_path)),
                ('districts', models.ManyToManyField(blank=True, related_name='shape_image', to='index.District')),
            ],
        ),
    ]
