# Generated by Django 3.0.2 on 2020-07-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200723_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shapeimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
