# Generated by Django 3.0.2 on 2020-07-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20200723_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shapeimage',
            name='name',
            field=models.CharField(default='Name', max_length=255),
            preserve_default=False,
        ),
    ]
